######################################################################
# Automatically generated by qmake (2.01a) Mon 20. May 00:36:53 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += lsystem.h mainwindow.h state.h turtle.h
SOURCES += lsystem.cpp main.cpp mainwindow.cpp state.cpp turtle.cpp
